"""Initial migration

Revision ID: e7e9db004113
Revises: 
Create Date: 2026-02-25 16:54:56.793656

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'e7e9db004113'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sources',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('url', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('source_type', sa.Enum('RSS', 'PLAYWRIGHT', 'API', name='sourcetype'), nullable=False),
    sa.Column('category_hint', sa.Enum('LLM', 'HARDWARE', 'POLICY', 'STARTUP', 'RESEARCH', 'STOCK', 'CRYPTO', 'GENERAL', name='categoryhint'), nullable=False),
    sa.Column('crawl_interval_minutes', sa.Integer(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('config', sa.JSON(), nullable=True),
    sa.Column('last_crawled_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sources_name'), 'sources', ['name'], unique=False)
    op.create_table('crawled_contents',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('source_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('content', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('summary_manual', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('image_urls', sa.JSON(), nullable=True),
    sa.Column('source_url', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('published_at', sa.DateTime(), nullable=False),
    sa.Column('extra_data', sa.JSON(), nullable=True),
    sa.Column('category_hint', sa.Enum('LLM', 'HARDWARE', 'POLICY', 'STARTUP', 'RESEARCH', 'STOCK', 'CRYPTO', 'GENERAL', name='categoryhint'), nullable=False),
    sa.Column('thread_status', sa.Enum('PENDING', 'ANALYZING', 'READY', 'PUBLISHED', 'FAILED', name='threadstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_url')
    )
    op.create_index(op.f('ix_crawled_contents_source_id'), 'crawled_contents', ['source_id'], unique=False)
    op.create_table('threads',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('source_content_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('content', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('image_urls', sa.JSON(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'ANALYZING', 'READY', 'SCHEDULED', 'PUBLISHED', 'FAILED', name='threadstatus'), nullable=False),
    sa.Column('scheduled_at', sa.DateTime(), nullable=True),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.Column('threads_post_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('extra_data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['source_content_id'], ['crawled_contents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_threads_source_content_id'), 'threads', ['source_content_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_threads_source_content_id'), table_name='threads')
    op.drop_table('threads')
    op.drop_index(op.f('ix_crawled_contents_source_id'), table_name='crawled_contents')
    op.drop_table('crawled_contents')
    op.drop_index(op.f('ix_sources_name'), table_name='sources')
    op.drop_table('sources')
    # ### end Alembic commands ###
